try:
    10/0
except Exception as e:
    print("Ocurri√≥ un error", e)
    
print("continuamos")    